# Análisis Exploratorio y Limpieza de Datos del Dataset de Salud

Este notebook sigue un flujo profesional de análisis de datos en dos fases:

- **Fase 1: Exploración y Diagnóstico**
- **Fase 2: Limpieza y Transformación**

Cada decisión de limpieza está justificada y documentada.

In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in c:\users\james\appdata\roaming\python\python313\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\james\appdata\roaming\python\python313\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (6.32.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\james\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\james\appdata\roaming\python\python313\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
import numpy as np
import pandas as pd
import kagglehub

## Fase 1 — Exploración y Diagnóstico del Dataset

Antes de limpiar cualquier dato, se realiza una exploración inicial y se documentan los problemas encontrados.

In [66]:
path = kagglehub.dataset_download("prasad22/healthcare-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\james\.cache\kagglehub\datasets\prasad22\healthcare-dataset\versions\2

In [67]:
datase = pd.read_csv("healthcare_dataset.csv")
datase

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

### Diagnóstico inicial
- Se exploran los tipos de datos, valores nulos, duplicados y estadísticas básicas.

In [68]:
datase.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [69]:
datase.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

#### Problemas detectados en la exploración:
- Existen valores nulos en algunas columnas.
- Hay filas duplicadas.
- Las columnas de fechas están como tipo object.
- Existen montos de 'Billing Amount' negativos o sospechosamente bajos (< $100).
- Hay pacientes menores de 18 años.
- El campo 'Hospital' tiene nombres inconsistentes.

In [70]:
datase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [71]:
datase.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [72]:
datase.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [73]:
datase[datase.duplicated(keep=False)].sort_values(by='Name')

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
54285,ABIgaIL YOung,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
42407,ABIgaIL YOung,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
26025,ALIcia taYLoR,78,Male,O+,Asthma,2022-09-18,Dawn Burton,Wright LLC,Aetna,31465.274979,149,Elective,2022-10-15,Aspirin,Inconclusive
53104,ALIcia taYLoR,78,Male,O+,Asthma,2022-09-18,Dawn Burton,Wright LLC,Aetna,31465.274979,149,Elective,2022-10-15,Aspirin,Inconclusive
50151,AMy GREEN,79,Female,B+,Obesity,2021-03-30,Brett Johnson,Taylor-Williamson,UnitedHealthcare,23402.358491,249,Elective,2021-04-27,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50070,wiLliam LEe,27,Female,O+,Arthritis,2020-01-31,Lauren Montgomery,Winters-Simon,Cigna,46229.434901,153,Elective,2020-02-13,Lipitor,Normal
53693,willIAM DUnCan,78,Female,B-,Arthritis,2019-08-04,Margaret Rice,"and Hobbs Rice, Miller",UnitedHealthcare,4537.845577,383,Elective,2019-08-17,Aspirin,Abnormal
27374,willIAM DUnCan,78,Female,B-,Arthritis,2019-08-04,Margaret Rice,"and Hobbs Rice, Miller",UnitedHealthcare,4537.845577,383,Elective,2019-08-17,Aspirin,Abnormal
51964,zaCHAry balL,85,Female,B-,Diabetes,2020-04-25,Matthew Conley,"and Morgan Jones, Matthews",Blue Cross,15207.547262,202,Emergency,2020-05-25,Penicillin,Inconclusive
6345,zaCHAry balL,85,Female,B-,Diabetes,2020-04-25,Matthew Conley,"and Morgan Jones, Matthews",Blue Cross,15207.547262,202,Emergency,2020-05-25,Penicillin,Inconclusive

In [74]:
datase.drop_duplicates(inplace=True)

In [75]:
datase.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  object
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  object
 3   Blood Type          54966 non-null  object
 4   Medical Condition   54966 non-null  object
 5   Date of Admission   54966 non-null  object
 6   Doctor              54966 non-null  object
 7   Hospital            54966 non-null  object
 8   Insurance Provider  54966 non-null  object
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  object
 12  Discharge Date      54966 non-null  object
 13  Medication          54966 non-null  object
 14  Test Results        54966 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.7+ MB

In [76]:
datase['Date of Admission'] = pd.to_datetime(datase['Date of Admission'])
datase['Discharge Date'] = pd.to_datetime(datase['Discharge Date'])

In [77]:
datase.describe()

,Age,Date of Admission,Billing Amount,Room Number,Discharge Date
count,54966.000000,54966,54966.000000,54966.000000,54966
mean,51.535185,2021-11-01 17:35:29.505512448,25544.306284,301.124404,2021-11-17 05:34:28.202161408
min,13.000000,2019-05-08 00:00:00,-2008.492140,101.000000,2019-05-09 00:00:00
25%,35.000000,2020-07-28 00:00:00,13243.718641,202.000000,2020-08-13 00:00:00
50%,52.000000,2021-11-02 00:00:00,25542.749145,302.000000,2021-11-18 00:00:00
75%,68.000000,2023-02-03 00:00:00,37819.858159,401.000000,2023-02-19 00:00:00
max,89.000000,2024-05-07 00:00:00,52764.276736,500.000000,2024-06-06 00:00:00
std,19.605661,NaN,14208.409711,115.223143,NaN

In [78]:
datase['Name'] = datase['Name'].str.title()
datase[['Name']].head()

            Name
0  Bobby Jackson
1   Leslie Terry
2    Danny Smith
3   Andrew Watts
4  Adrienne Bell

In [79]:
datase['Hospital'] = datase['Hospital'].str.replace('-', ' ', regex=False)
datase['Hospital'] = datase['Hospital'].str.replace(',', '', regex=False)
datase['Hospital'] = datase['Hospital'].str.title()
datase[['Hospital']].drop_duplicates().head()

                    Hospital
0            Sons And Miller
1                    Kim Inc
2                   Cook Plc
3  Hernandez Rogers And Vang
4                White White

In [80]:
datase['Name'].nunique()

40235

In [81]:
datase

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons And Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook Plc,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers And Vang,Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,And Mahoney Johnson Vasquez,UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,Jackson Todd And Castro,Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons And,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [82]:
cat_cols = datase.select_dtypes(include=['object']).columns
cat_cols

Index(['Name', 'Gender', 'Blood Type', 'Medical Condition', 'Doctor',
       'Hospital', 'Insurance Provider', 'Admission Type', 'Medication',
       'Test Results'],
      dtype='object')

## Fase 2 — Limpieza y Transformación

A continuación se aplican las transformaciones necesarias para obtener un dataset limpio y consistente. Cada paso está justificado.

In [83]:
datase = datase[datase['Billing Amount'] >= 0].copy()
datase.reset_index(drop=True, inplace=True)
datase['Billing Amount'].describe()

count    54860.000000
mean     25594.633637
std      14175.867041
min          9.238787
25%      13299.747940
50%      25593.873000
75%      37847.066671
max      52764.276736
Name: Billing Amount, dtype: float64

> **Nota:** Los valores bajos en 'Billing Amount' pueden corresponder a pagos de medicamentos u otros servicios menores, por lo que no se eliminan automáticamente del dataset. Esta decisión se toma para evitar perder información potencialmente relevante para el análisis.

**Justificación:** Se eliminan registros con 'Billing Amount' negativo porque no tienen sentido en el contexto hospitalario. Se resetea el índice para evitar inconsistencias.

In [84]:
import re
def limpiar_prefijo(nombre):
    if isinstance(nombre, str):
        return re.sub(r'^(mr\.?|mrs\.?|ms\.?|miss|dr\.?|prof\.?|sr\.?|sra\.?|mx\.?|mtro\.?|lic\.?|ing\.?|dra\.?|fr\.?|rev\.?|capt\.?|col\.?|maj\.?|lt\.?|sgt\.?|cpt\.?|cmdr\.?|adm\.?|ofc\.?|pres\.?|gov\.?|sen\.?|rep\.?|amb\.?|treas\.?|sec\.?|pvt\.?|hon\.?|judge|arq\.?|qfb\.?|mc\.?|phd\.?|ph\.d\.?|m\.d\.?|d\.d\.s\.?|dvm\.?|esq\.?|srta\.?|srto\.?|licda\.?|licdo\.?|licenciado|licenciada|doctor|doctora|ingeniero|ingeniera|arquitecto|arquitecta|profesor|profesora|fray|hermano|hermana|padre|monja|reverendo|reverenda|capitán|coronel|mayor|teniente|sargento|comandante|almirante|oficial|presidente|gobernador|senador|representante|embajador|tesorero|secretario|privado|honorable|juez)\s+', '', nombre, flags=re.IGNORECASE).strip()
    return nombre
datase.loc[:, 'Name'] = datase['Name'].apply(limpiar_prefijo)
datase[['Name']]

                    Name
0          Bobby Jackson
1           Leslie Terry
2            Danny Smith
3           Andrew Watts
4          Adrienne Bell
...                  ...
54855  Elizabeth Jackson
54856         Kyle Perez
54857       Heather Wang
54858     Jennifer Jones
54859       James Garcia

[54860 rows x 1 columns]

**Justificación:** Se limpian los prefijos de títulos en los nombres para estandarizar la columna 'Name'.

In [85]:
datase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54860 entries, 0 to 54859
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54860 non-null  object
 1   Age                 54860 non-null  int64
 2   Gender              54860 non-null  object
 3   Blood Type          54860 non-null  object
 4   Medical Condition   54860 non-null  object
 5   Date of Admission   54860 non-null  datetime64[ns]
 6   Doctor              54860 non-null  object
 7   Hospital            54860 non-null  object
 8   Insurance Provider  54860 non-null  object
 9   Billing Amount      54860 non-null  float64
 10  Room Number         54860 non-null  int64
 11  Admission Type      54860 non-null  object
 12  Discharge Date      54860 non-null  datetime64[ns]
 13  Medication          54860 non-null  object
 14  Test Results        54860 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.3+ MB

In [86]:
import re

def limpiar_and(nombre):
    if isinstance(nombre, str):
        return re.sub(r'^(And\s+)|(\s+And)$', '', nombre, flags=re.IGNORECASE).strip()
    return nombre
datase['Hospital'] = datase['Hospital'].apply(limpiar_and)

datase['Hospital'].unique()[:10]

array(['Sons And Miller', 'Kim Inc', 'Cook Plc',
       'Hernandez Rogers And Vang', 'White White', 'Nunez Humphrey',
       'Group Middleton', 'Powell Robinson And Valdez', 'Sons Rich',
       'Padilla Walker'], dtype=object)

**Justificación:** Se limpian inconsistencias en los nombres de hospitales para facilitar análisis posteriores.

In [87]:
datase

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons And Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook Plc,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers And Vang,Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54855,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
54856,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
54857,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,Mahoney Johnson Vasquez,UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
54858,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,Jackson Todd And Castro,Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
54859,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [88]:

def limpiar_prefijo(nombre):
    import re
    if isinstance(nombre, str):
        return re.sub(r'^(mr|mrs|ms|dr|miss|sr|sra|srta)\.?\s+', '', nombre, flags=re.IGNORECASE).strip()
    return nombre

datase['Name'] = datase['Name'].apply(limpiar_prefijo)

datase['Name'].head(10)

0         Bobby Jackson
1          Leslie Terry
2           Danny Smith
3          Andrew Watts
4         Adrienne Bell
5         Emily Johnson
6        Edward Edwards
7    Christina Martinez
8       Jasmine Aguilar
9      Christopher Berg
Name: Name, dtype: object

In [96]:
datase.to_csv('healthcare_dataset_limpio.csv', index=False)